///************************************************
/// Generated by: linhdh
/// Date: 19/09/2011 12:46:50
/// Goal: Create User Service Class for V_DM_GIANG_VIEN
///************************************************
/// <summary>
/// Create User Service Class for V_DM_GIANG_VIEN
/// </summary>

using System;
using AuctionDS;
using IP.Core.IPCommon;
using IP.Core.IPUserService;
using System.Data.SqlClient;
using System.Data;
using WebDS;


namespace AuctionUS{

public class US_V_DM_GIANG_VIEN : US_Object
{
	private const string c_TableName = "V_DM_GIANG_VIEN";
#region "Public Properties"
	public string strMA_GIANG_VIEN 
	{
		get 
		{
			return CNull.RowNVLString(pm_objDR, "MA_GIANG_VIEN", IPConstants.c_DefaultString);
		}
		set 
		{
			pm_objDR["MA_GIANG_VIEN"] = value;
		}
	}

	public bool IsMA_GIANG_VIENNull() 
	{
		return pm_objDR.IsNull("MA_GIANG_VIEN");
	}

	public void SetMA_GIANG_VIENNull() {
		pm_objDR["MA_GIANG_VIEN"] = System.Convert.DBNull;
	}

	public string strHO_VA_TEN_DEM 
	{
		get 
		{
			return CNull.RowNVLString(pm_objDR, "HO_VA_TEN_DEM", IPConstants.c_DefaultString);
		}
		set 
		{
			pm_objDR["HO_VA_TEN_DEM"] = value;
		}
	}

	public bool IsHO_VA_TEN_DEMNull() 
	{
		return pm_objDR.IsNull("HO_VA_TEN_DEM");
	}

	public void SetHO_VA_TEN_DEMNull() {
		pm_objDR["HO_VA_TEN_DEM"] = System.Convert.DBNull;
	}

	public string strTEN_GIANG_VIEN 
	{
		get 
		{
			return CNull.RowNVLString(pm_objDR, "TEN_GIANG_VIEN", IPConstants.c_DefaultString);
		}
		set 
		{
			pm_objDR["TEN_GIANG_VIEN"] = value;
		}
	}

	public bool IsTEN_GIANG_VIENNull() 
	{
		return pm_objDR.IsNull("TEN_GIANG_VIEN");
	}

	public void SetTEN_GIANG_VIENNull() {
		pm_objDR["TEN_GIANG_VIEN"] = System.Convert.DBNull;
	}

	public DateTime datNGAY_SINH
	{
		get   
		{
			return CNull.RowNVLDate(pm_objDR, "NGAY_SINH", IPConstants.c_DefaultDate);
		}
		set   
		{
			pm_objDR["NGAY_SINH"] = value;
		}
	}

	public bool IsNGAY_SINHNull()
	{
		return pm_objDR.IsNull("NGAY_SINH");
	}

	public void SetNGAY_SINHNull()
	{
		pm_objDR["NGAY_SINH"] = System.Convert.DBNull;
	}

	public string strGIOI_TINH_YN 
	{
		get 
		{
			return CNull.RowNVLString(pm_objDR, "GIOI_TINH_YN", IPConstants.c_DefaultString);
		}
		set 
		{
			pm_objDR["GIOI_TINH_YN"] = value;
		}
	}

	public bool IsGIOI_TINH_YNNull() 
	{
		return pm_objDR.IsNull("GIOI_TINH_YN");
	}

	public void SetGIOI_TINH_YNNull() {
		pm_objDR["GIOI_TINH_YN"] = System.Convert.DBNull;
	}

	public string strCHUC_VU_HIEN_TAI 
	{
		get 
		{
			return CNull.RowNVLString(pm_objDR, "CHUC_VU_HIEN_TAI", IPConstants.c_DefaultString);
		}
		set 
		{
			pm_objDR["CHUC_VU_HIEN_TAI"] = value;
		}
	}

	public bool IsCHUC_VU_HIEN_TAINull() 
	{
		return pm_objDR.IsNull("CHUC_VU_HIEN_TAI");
	}

	public void SetCHUC_VU_HIEN_TAINull() {
		pm_objDR["CHUC_VU_HIEN_TAI"] = System.Convert.DBNull;
	}

	public string strCHUC_VU_CAO_NHAT 
	{
		get 
		{
			return CNull.RowNVLString(pm_objDR, "CHUC_VU_CAO_NHAT", IPConstants.c_DefaultString);
		}
		set 
		{
			pm_objDR["CHUC_VU_CAO_NHAT"] = value;
		}
	}

	public bool IsCHUC_VU_CAO_NHATNull() 
	{
		return pm_objDR.IsNull("CHUC_VU_CAO_NHAT");
	}

	public void SetCHUC_VU_CAO_NHATNull() {
		pm_objDR["CHUC_VU_CAO_NHAT"] = System.Convert.DBNull;
	}

	public string strTEL_HOME 
	{
		get 
		{
			return CNull.RowNVLString(pm_objDR, "TEL_HOME", IPConstants.c_DefaultString);
		}
		set 
		{
			pm_objDR["TEL_HOME"] = value;
		}
	}

	public bool IsTEL_HOMENull() 
	{
		return pm_objDR.IsNull("TEL_HOME");
	}

	public void SetTEL_HOMENull() {
		pm_objDR["TEL_HOME"] = System.Convert.DBNull;
	}

	public string strTEL_OFFICE 
	{
		get 
		{
			return CNull.RowNVLString(pm_objDR, "TEL_OFFICE", IPConstants.c_DefaultString);
		}
		set 
		{
			pm_objDR["TEL_OFFICE"] = value;
		}
	}

	public bool IsTEL_OFFICENull() 
	{
		return pm_objDR.IsNull("TEL_OFFICE");
	}

	public void SetTEL_OFFICENull() {
		pm_objDR["TEL_OFFICE"] = System.Convert.DBNull;
	}

	public string strMOBILE_PHONE 
	{
		get 
		{
			return CNull.RowNVLString(pm_objDR, "MOBILE_PHONE", IPConstants.c_DefaultString);
		}
		set 
		{
			pm_objDR["MOBILE_PHONE"] = value;
		}
	}

	public bool IsMOBILE_PHONENull() 
	{
		return pm_objDR.IsNull("MOBILE_PHONE");
	}

	public void SetMOBILE_PHONENull() {
		pm_objDR["MOBILE_PHONE"] = System.Convert.DBNull;
	}

	public string strEMAIL 
	{
		get 
		{
			return CNull.RowNVLString(pm_objDR, "EMAIL", IPConstants.c_DefaultString);
		}
		set 
		{
			pm_objDR["EMAIL"] = value;
		}
	}

	public bool IsEMAILNull() 
	{
		return pm_objDR.IsNull("EMAIL");
	}

	public void SetEMAILNull() {
		pm_objDR["EMAIL"] = System.Convert.DBNull;
	}

	public string strTEN_CO_QUAN_CONG_TAC 
	{
		get 
		{
			return CNull.RowNVLString(pm_objDR, "TEN_CO_QUAN_CONG_TAC", IPConstants.c_DefaultString);
		}
		set 
		{
			pm_objDR["TEN_CO_QUAN_CONG_TAC"] = value;
		}
	}

	public bool IsTEN_CO_QUAN_CONG_TACNull() 
	{
		return pm_objDR.IsNull("TEN_CO_QUAN_CONG_TAC");
	}

	public void SetTEN_CO_QUAN_CONG_TACNull() {
		pm_objDR["TEN_CO_QUAN_CONG_TAC"] = System.Convert.DBNull;
	}

	public string strEMAIL_TOPICA 
	{
		get 
		{
			return CNull.RowNVLString(pm_objDR, "EMAIL_TOPICA", IPConstants.c_DefaultString);
		}
		set 
		{
			pm_objDR["EMAIL_TOPICA"] = value;
		}
	}

	public bool IsEMAIL_TOPICANull() 
	{
		return pm_objDR.IsNull("EMAIL_TOPICA");
	}

	public void SetEMAIL_TOPICANull() {
		pm_objDR["EMAIL_TOPICA"] = System.Convert.DBNull;
	}

	public string strANH_CA_NHAN 
	{
		get 
		{
			return CNull.RowNVLString(pm_objDR, "ANH_CA_NHAN", IPConstants.c_DefaultString);
		}
		set 
		{
			pm_objDR["ANH_CA_NHAN"] = value;
		}
	}

	public bool IsANH_CA_NHANNull() 
	{
		return pm_objDR.IsNull("ANH_CA_NHAN");
	}

	public void SetANH_CA_NHANNull() {
		pm_objDR["ANH_CA_NHAN"] = System.Convert.DBNull;
	}

	public string strHOC_VI 
	{
		get 
		{
			return CNull.RowNVLString(pm_objDR, "HOC_VI", IPConstants.c_DefaultString);
		}
		set 
		{
			pm_objDR["HOC_VI"] = value;
		}
	}

	public bool IsHOC_VINull() 
	{
		return pm_objDR.IsNull("HOC_VI");
	}

	public void SetHOC_VINull() {
		pm_objDR["HOC_VI"] = System.Convert.DBNull;
	}

	public string strHOC_HAM 
	{
		get 
		{
			return CNull.RowNVLString(pm_objDR, "HOC_HAM", IPConstants.c_DefaultString);
		}
		set 
		{
			pm_objDR["HOC_HAM"] = value;
		}
	}

	public bool IsHOC_HAMNull() 
	{
		return pm_objDR.IsNull("HOC_HAM");
	}

	public void SetHOC_HAMNull() {
		pm_objDR["HOC_HAM"] = System.Convert.DBNull;
	}

	public string strCHUYEN_NGANH_CHINH 
	{
		get 
		{
			return CNull.RowNVLString(pm_objDR, "CHUYEN_NGANH_CHINH", IPConstants.c_DefaultString);
		}
		set 
		{
			pm_objDR["CHUYEN_NGANH_CHINH"] = value;
		}
	}

	public bool IsCHUYEN_NGANH_CHINHNull() 
	{
		return pm_objDR.IsNull("CHUYEN_NGANH_CHINH");
	}

	public void SetCHUYEN_NGANH_CHINHNull() {
		pm_objDR["CHUYEN_NGANH_CHINH"] = System.Convert.DBNull;
	}

	public string strTRUONG_DAO_TAO 
	{
		get 
		{
			return CNull.RowNVLString(pm_objDR, "TRUONG_DAO_TAO", IPConstants.c_DefaultString);
		}
		set 
		{
			pm_objDR["TRUONG_DAO_TAO"] = value;
		}
	}

	public bool IsTRUONG_DAO_TAONull() 
	{
		return pm_objDR.IsNull("TRUONG_DAO_TAO");
	}

	public void SetTRUONG_DAO_TAONull() {
		pm_objDR["TRUONG_DAO_TAO"] = System.Convert.DBNull;
	}

	public string strID_TRANG_THAI_GIANG_VIEN 
	{
		get 
		{
			return CNull.RowNVLString(pm_objDR, "ID_TRANG_THAI_GIANG_VIEN", IPConstants.c_DefaultString);
		}
		set 
		{
			pm_objDR["ID_TRANG_THAI_GIANG_VIEN"] = value;
		}
	}

	public bool IsID_TRANG_THAI_GIANG_VIENNull() 
	{
		return pm_objDR.IsNull("ID_TRANG_THAI_GIANG_VIEN");
	}

	public void SetID_TRANG_THAI_GIANG_VIENNull() {
		pm_objDR["ID_TRANG_THAI_GIANG_VIEN"] = System.Convert.DBNull;
	}

	public string strTRANG_THAI_GIANG_VIEN 
	{
		get 
		{
			return CNull.RowNVLString(pm_objDR, "TRANG_THAI_GIANG_VIEN", IPConstants.c_DefaultString);
		}
		set 
		{
			pm_objDR["TRANG_THAI_GIANG_VIEN"] = value;
		}
	}

	public bool IsTRANG_THAI_GIANG_VIENNull() 
	{
		return pm_objDR.IsNull("TRANG_THAI_GIANG_VIEN");
	}

	public void SetTRANG_THAI_GIANG_VIENNull() {
		pm_objDR["TRANG_THAI_GIANG_VIEN"] = System.Convert.DBNull;
	}

	public string strSO_TAI_KHOAN 
	{
		get 
		{
			return CNull.RowNVLString(pm_objDR, "SO_TAI_KHOAN", IPConstants.c_DefaultString);
		}
		set 
		{
			pm_objDR["SO_TAI_KHOAN"] = value;
		}
	}

	public bool IsSO_TAI_KHOANNull() 
	{
		return pm_objDR.IsNull("SO_TAI_KHOAN");
	}

	public void SetSO_TAI_KHOANNull() {
		pm_objDR["SO_TAI_KHOAN"] = System.Convert.DBNull;
	}

	public string strTEN_NGAN_HANG 
	{
		get 
		{
			return CNull.RowNVLString(pm_objDR, "TEN_NGAN_HANG", IPConstants.c_DefaultString);
		}
		set 
		{
			pm_objDR["TEN_NGAN_HANG"] = value;
		}
	}

	public bool IsTEN_NGAN_HANGNull() 
	{
		return pm_objDR.IsNull("TEN_NGAN_HANG");
	}

	public void SetTEN_NGAN_HANGNull() {
		pm_objDR["TEN_NGAN_HANG"] = System.Convert.DBNull;
	}

	public string strSO_CMTND 
	{
		get 
		{
			return CNull.RowNVLString(pm_objDR, "SO_CMTND", IPConstants.c_DefaultString);
		}
		set 
		{
			pm_objDR["SO_CMTND"] = value;
		}
	}

	public bool IsSO_CMTNDNull() 
	{
		return pm_objDR.IsNull("SO_CMTND");
	}

	public void SetSO_CMTNDNull() {
		pm_objDR["SO_CMTND"] = System.Convert.DBNull;
	}

	public DateTime datNGAY_CAP
	{
		get   
		{
			return CNull.RowNVLDate(pm_objDR, "NGAY_CAP", IPConstants.c_DefaultDate);
		}
		set   
		{
			pm_objDR["NGAY_CAP"] = value;
		}
	}

	public bool IsNGAY_CAPNull()
	{
		return pm_objDR.IsNull("NGAY_CAP");
	}

	public void SetNGAY_CAPNull()
	{
		pm_objDR["NGAY_CAP"] = System.Convert.DBNull;
	}

	public string strNOI_CAP 
	{
		get 
		{
			return CNull.RowNVLString(pm_objDR, "NOI_CAP", IPConstants.c_DefaultString);
		}
		set 
		{
			pm_objDR["NOI_CAP"] = value;
		}
	}

	public bool IsNOI_CAPNull() 
	{
		return pm_objDR.IsNull("NOI_CAP");
	}

	public void SetNOI_CAPNull() {
		pm_objDR["NOI_CAP"] = System.Convert.DBNull;
	}

	public decimal dcID_DON_VI_QUAN_LY 
	{
		get
		{
			return CNull.RowNVLDecimal(pm_objDR, "ID_DON_VI_QUAN_LY", IPConstants.c_DefaultDecimal);
		}
		set	
		{
			pm_objDR["ID_DON_VI_QUAN_LY"] = value;
		}
	}

	public bool IsID_DON_VI_QUAN_LYNull()	{
		return pm_objDR.IsNull("ID_DON_VI_QUAN_LY");
	}

	public void SetID_DON_VI_QUAN_LYNull() {
		pm_objDR["ID_DON_VI_QUAN_LY"] = System.Convert.DBNull;
	}

	public string strDON_VI_QUAN_LY 
	{
		get 
		{
			return CNull.RowNVLString(pm_objDR, "DON_VI_QUAN_LY", IPConstants.c_DefaultString);
		}
		set 
		{
			pm_objDR["DON_VI_QUAN_LY"] = value;
		}
	}

	public bool IsDON_VI_QUAN_LYNull() 
	{
		return pm_objDR.IsNull("DON_VI_QUAN_LY");
	}

	public void SetDON_VI_QUAN_LYNull() {
		pm_objDR["DON_VI_QUAN_LY"] = System.Convert.DBNull;
	}

	public string strMA_SO_THUE 
	{
		get 
		{
			return CNull.RowNVLString(pm_objDR, "MA_SO_THUE", IPConstants.c_DefaultString);
		}
		set 
		{
			pm_objDR["MA_SO_THUE"] = value;
		}
	}

	public bool IsMA_SO_THUENull() 
	{
		return pm_objDR.IsNull("MA_SO_THUE");
	}

	public void SetMA_SO_THUENull() {
		pm_objDR["MA_SO_THUE"] = System.Convert.DBNull;
	}

	public string strGVHD_YN 
	{
		get 
		{
			return CNull.RowNVLString(pm_objDR, "GVHD_YN", IPConstants.c_DefaultString);
		}
		set 
		{
			pm_objDR["GVHD_YN"] = value;
		}
	}

	public bool IsGVHD_YNNull() 
	{
		return pm_objDR.IsNull("GVHD_YN");
	}

	public void SetGVHD_YNNull() {
		pm_objDR["GVHD_YN"] = System.Convert.DBNull;
	}

	public string strGVCM_YN 
	{
		get 
		{
			return CNull.RowNVLString(pm_objDR, "GVCM_YN", IPConstants.c_DefaultString);
		}
		set 
		{
			pm_objDR["GVCM_YN"] = value;
		}
	}

	public bool IsGVCM_YNNull() 
	{
		return pm_objDR.IsNull("GVCM_YN");
	}

	public void SetGVCM_YNNull() {
		pm_objDR["GVCM_YN"] = System.Convert.DBNull;
	}

	public string strGV_VIET_HL_YN 
	{
		get 
		{
			return CNull.RowNVLString(pm_objDR, "GV_VIET_HL_YN", IPConstants.c_DefaultString);
		}
		set 
		{
			pm_objDR["GV_VIET_HL_YN"] = value;
		}
	}

	public bool IsGV_VIET_HL_YNNull() 
	{
		return pm_objDR.IsNull("GV_VIET_HL_YN");
	}

	public void SetGV_VIET_HL_YNNull() {
		pm_objDR["GV_VIET_HL_YN"] = System.Convert.DBNull;
	}

	public string strGV_DUYET_HL_YN 
	{
		get 
		{
			return CNull.RowNVLString(pm_objDR, "GV_DUYET_HL_YN", IPConstants.c_DefaultString);
		}
		set 
		{
			pm_objDR["GV_DUYET_HL_YN"] = value;
		}
	}

	public bool IsGV_DUYET_HL_YNNull() 
	{
		return pm_objDR.IsNull("GV_DUYET_HL_YN");
	}

	public void SetGV_DUYET_HL_YNNull() {
		pm_objDR["GV_DUYET_HL_YN"] = System.Convert.DBNull;
	}

	public string strGV_THAM_DINH_HL_YN 
	{
		get 
		{
			return CNull.RowNVLString(pm_objDR, "GV_THAM_DINH_HL_YN", IPConstants.c_DefaultString);
		}
		set 
		{
			pm_objDR["GV_THAM_DINH_HL_YN"] = value;
		}
	}

	public bool IsGV_THAM_DINH_HL_YNNull() 
	{
		return pm_objDR.IsNull("GV_THAM_DINH_HL_YN");
	}

	public void SetGV_THAM_DINH_HL_YNNull() {
		pm_objDR["GV_THAM_DINH_HL_YN"] = System.Convert.DBNull;
	}

	public string strGV_HDKH_YN 
	{
		get 
		{
			return CNull.RowNVLString(pm_objDR, "GV_HDKH_YN", IPConstants.c_DefaultString);
		}
		set 
		{
			pm_objDR["GV_HDKH_YN"] = value;
		}
	}

	public bool IsGV_HDKH_YNNull() 
	{
		return pm_objDR.IsNull("GV_HDKH_YN");
	}

	public void SetGV_HDKH_YNNull() {
		pm_objDR["GV_HDKH_YN"] = System.Convert.DBNull;
	}

	public string strDESCRIPTION 
	{
		get 
		{
			return CNull.RowNVLString(pm_objDR, "DESCRIPTION", IPConstants.c_DefaultString);
		}
		set 
		{
			pm_objDR["DESCRIPTION"] = value;
		}
	}

	public bool IsDESCRIPTIONNull() 
	{
		return pm_objDR.IsNull("DESCRIPTION");
	}

	public void SetDESCRIPTIONNull() {
		pm_objDR["DESCRIPTION"] = System.Convert.DBNull;
	}

#endregion
#region "Init Functions"
	public US_V_DM_GIANG_VIEN() 
	{
		pm_objDS = new DS_V_DM_GIANG_VIEN();
		pm_strTableName = c_TableName;
		pm_objDR = pm_objDS.Tables[pm_strTableName].NewRow();
	}

	public US_V_DM_GIANG_VIEN(DataRow i_objDR): this()
	{
		this.DataRow2Me(i_objDR);
	}

	public US_V_DM_GIANG_VIEN(decimal i_dbID) 
	{
		pm_objDS = new DS_V_DM_GIANG_VIEN();
		pm_strTableName = c_TableName;
		IMakeSelectCmd v_objMkCmd = new CMakeAndSelectCmd(pm_objDS, c_TableName);
		v_objMkCmd.AddCondition("ID", i_dbID, eKieuDuLieu.KieuNumber, eKieuSoSanh.Bang);
		SqlCommand v_cmdSQL;
		v_cmdSQL = v_objMkCmd.getSelectCmd();
		this.FillDatasetByCommand(pm_objDS, v_cmdSQL);
		pm_objDR = getRowClone(pm_objDS.Tables[pm_strTableName].Rows[0]);
	}
#endregion
	}
}
