///************************************************
/// Generated by: linhdh
/// Date: 15/11/2011 03:37:05
/// Goal: Create User Service Class for V_GD_THANH_TOAN
///************************************************
/// <summary>
/// Create User Service Class for V_GD_THANH_TOAN
/// </summary>

using System;
using IP.Core.IPCommon;
using IP.Core.IPUserService;
using System.Data.SqlClient;
using System.Data;
using WebDS;


namespace WebUS{

public class US_V_GD_THANH_TOAN : US_Object
{
	private const string c_TableName = "V_GD_THANH_TOAN";
#region "Public Properties"
	public decimal dcID 
	{
		get
		{
			return CNull.RowNVLDecimal(pm_objDR, "ID", IPConstants.c_DefaultDecimal);
		}
		set	
		{
			pm_objDR["ID"] = value;
		}
	}

	public bool IsIDNull()	{
		return pm_objDR.IsNull("ID");
	}

	public void SetIDNull() {
		pm_objDR["ID"] = System.Convert.DBNull;
	}

	public string strSO_PHIEU_THANH_TOAN 
	{
		get 
		{
			return CNull.RowNVLString(pm_objDR, "SO_PHIEU_THANH_TOAN", IPConstants.c_DefaultString);
		}
		set 
		{
			pm_objDR["SO_PHIEU_THANH_TOAN"] = value;
		}
	}

	public bool IsSO_PHIEU_THANH_TOANNull() 
	{
		return pm_objDR.IsNull("SO_PHIEU_THANH_TOAN");
	}

	public void SetSO_PHIEU_THANH_TOANNull() {
		pm_objDR["SO_PHIEU_THANH_TOAN"] = System.Convert.DBNull;
	}

	public decimal dcID_HOP_DONG_KHUNG 
	{
		get
		{
			return CNull.RowNVLDecimal(pm_objDR, "ID_HOP_DONG_KHUNG", IPConstants.c_DefaultDecimal);
		}
		set	
		{
			pm_objDR["ID_HOP_DONG_KHUNG"] = value;
		}
	}

	public bool IsID_HOP_DONG_KHUNGNull()	{
		return pm_objDR.IsNull("ID_HOP_DONG_KHUNG");
	}

	public void SetID_HOP_DONG_KHUNGNull() {
		pm_objDR["ID_HOP_DONG_KHUNG"] = System.Convert.DBNull;
	}

	public decimal dcID_GIANG_VIEN 
	{
		get
		{
			return CNull.RowNVLDecimal(pm_objDR, "ID_GIANG_VIEN", IPConstants.c_DefaultDecimal);
		}
		set	
		{
			pm_objDR["ID_GIANG_VIEN"] = value;
		}
	}

	public bool IsID_GIANG_VIENNull()	{
		return pm_objDR.IsNull("ID_GIANG_VIEN");
	}

	public void SetID_GIANG_VIENNull() {
		pm_objDR["ID_GIANG_VIEN"] = System.Convert.DBNull;
	}

	public string strMA_LOP_MON 
	{
		get 
		{
			return CNull.RowNVLString(pm_objDR, "MA_LOP_MON", IPConstants.c_DefaultString);
		}
		set 
		{
			pm_objDR["MA_LOP_MON"] = value;
		}
	}

	public bool IsMA_LOP_MONNull() 
	{
		return pm_objDR.IsNull("MA_LOP_MON");
	}

	public void SetMA_LOP_MONNull() {
		pm_objDR["MA_LOP_MON"] = System.Convert.DBNull;
	}

	public decimal dcID_MON_HOC 
	{
		get
		{
			return CNull.RowNVLDecimal(pm_objDR, "ID_MON_HOC", IPConstants.c_DefaultDecimal);
		}
		set	
		{
			pm_objDR["ID_MON_HOC"] = value;
		}
	}

	public bool IsID_MON_HOCNull()	{
		return pm_objDR.IsNull("ID_MON_HOC");
	}

	public void SetID_MON_HOCNull() {
		pm_objDR["ID_MON_HOC"] = System.Convert.DBNull;
	}

	public DateTime datNGAY_THANH_TOAN
	{
		get   
		{
			return CNull.RowNVLDate(pm_objDR, "NGAY_THANH_TOAN", IPConstants.c_DefaultDate);
		}
		set   
		{
			pm_objDR["NGAY_THANH_TOAN"] = value;
		}
	}

	public bool IsNGAY_THANH_TOANNull()
	{
		return pm_objDR.IsNull("NGAY_THANH_TOAN");
	}

	public void SetNGAY_THANH_TOANNull()
	{
		pm_objDR["NGAY_THANH_TOAN"] = System.Convert.DBNull;
	}

	public string strDESCRIPTION 
	{
		get 
		{
			return CNull.RowNVLString(pm_objDR, "DESCRIPTION", IPConstants.c_DefaultString);
		}
		set 
		{
			pm_objDR["DESCRIPTION"] = value;
		}
	}

	public bool IsDESCRIPTIONNull() 
	{
		return pm_objDR.IsNull("DESCRIPTION");
	}

	public void SetDESCRIPTIONNull() {
		pm_objDR["DESCRIPTION"] = System.Convert.DBNull;
	}

	public decimal dcTONG_TIEN_THANH_TOAN 
	{
		get
		{
			return CNull.RowNVLDecimal(pm_objDR, "TONG_TIEN_THANH_TOAN", IPConstants.c_DefaultDecimal);
		}
		set	
		{
			pm_objDR["TONG_TIEN_THANH_TOAN"] = value;
		}
	}

	public bool IsTONG_TIEN_THANH_TOANNull()	{
		return pm_objDR.IsNull("TONG_TIEN_THANH_TOAN");
	}

	public void SetTONG_TIEN_THANH_TOANNull() {
		pm_objDR["TONG_TIEN_THANH_TOAN"] = System.Convert.DBNull;
	}

	public decimal dcSO_TIEN_THUE 
	{
		get
		{
			return CNull.RowNVLDecimal(pm_objDR, "SO_TIEN_THUE", IPConstants.c_DefaultDecimal);
		}
		set	
		{
			pm_objDR["SO_TIEN_THUE"] = value;
		}
	}

	public bool IsSO_TIEN_THUENull()	{
		return pm_objDR.IsNull("SO_TIEN_THUE");
	}

	public void SetSO_TIEN_THUENull() {
		pm_objDR["SO_TIEN_THUE"] = System.Convert.DBNull;
	}

	public decimal dcTONG_TIEN_THUC_NHAN 
	{
		get
		{
			return CNull.RowNVLDecimal(pm_objDR, "TONG_TIEN_THUC_NHAN", IPConstants.c_DefaultDecimal);
		}
		set	
		{
			pm_objDR["TONG_TIEN_THUC_NHAN"] = value;
		}
	}

	public bool IsTONG_TIEN_THUC_NHANNull()	{
		return pm_objDR.IsNull("TONG_TIEN_THUC_NHAN");
	}

	public void SetTONG_TIEN_THUC_NHANNull() {
		pm_objDR["TONG_TIEN_THUC_NHAN"] = System.Convert.DBNull;
	}

	public string strREFERENCE_CODE 
	{
		get 
		{
			return CNull.RowNVLString(pm_objDR, "REFERENCE_CODE", IPConstants.c_DefaultString);
		}
		set 
		{
			pm_objDR["REFERENCE_CODE"] = value;
		}
	}

	public bool IsREFERENCE_CODENull() 
	{
		return pm_objDR.IsNull("REFERENCE_CODE");
	}

	public void SetREFERENCE_CODENull() {
		pm_objDR["REFERENCE_CODE"] = System.Convert.DBNull;
	}

	public decimal dcID_TRANG_THAI_THANH_TOAN 
	{
		get
		{
			return CNull.RowNVLDecimal(pm_objDR, "ID_TRANG_THAI_THANH_TOAN", IPConstants.c_DefaultDecimal);
		}
		set	
		{
			pm_objDR["ID_TRANG_THAI_THANH_TOAN"] = value;
		}
	}

	public bool IsID_TRANG_THAI_THANH_TOANNull()	{
		return pm_objDR.IsNull("ID_TRANG_THAI_THANH_TOAN");
	}

	public void SetID_TRANG_THAI_THANH_TOANNull() {
		pm_objDR["ID_TRANG_THAI_THANH_TOAN"] = System.Convert.DBNull;
	}

#endregion
#region "Init Functions"
	public US_V_GD_THANH_TOAN() 
	{
		pm_objDS = new DS_V_GD_THANH_TOAN();
		pm_strTableName = c_TableName;
		pm_objDR = pm_objDS.Tables[pm_strTableName].NewRow();
	}

	public US_V_GD_THANH_TOAN(DataRow i_objDR): this()
	{
		this.DataRow2Me(i_objDR);
	}

	public US_V_GD_THANH_TOAN(decimal i_dbID) 
	{
		pm_objDS = new DS_V_GD_THANH_TOAN();
		pm_strTableName = c_TableName;
		IMakeSelectCmd v_objMkCmd = new CMakeAndSelectCmd(pm_objDS, c_TableName);
		v_objMkCmd.AddCondition("ID", i_dbID, eKieuDuLieu.KieuNumber, eKieuSoSanh.Bang);
		SqlCommand v_cmdSQL;
		v_cmdSQL = v_objMkCmd.getSelectCmd();
		this.FillDatasetByCommand(pm_objDS, v_cmdSQL);
		pm_objDR = getRowClone(pm_objDS.Tables[pm_strTableName].Rows[0]);
	}
#endregion
	}
}
